/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package edu.ccsu.networking.ui;

import edu.ccsu.networking.main.*;
import javax.swing.*;
import java.io.File;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author Ben and Khaled
 */
public class ServerMenu extends javax.swing.JFrame {

    // VARIABLES
    Server server = new Server(this);
    private int port;
    
    DefaultTableModel model;
    
    // CONSTRUCTOR
    public ServerMenu(String port) { 
        super("FUN FILE SHARE - SERVER");
        this.setVisible(true); 
        initComponents();
        setLocationRelativeTo(this);
        
        model = (DefaultTableModel)directory_table.getModel();

        try
        {
            server.startSenderUDP(port);
            server.startReceiverUDP(port);
       }

        catch(Exception e)
        {
            System.out.println("INTERFACE - FAILED TO START SERVER UDP");
            //JOptionPane.showMessageDialog(null,"INTERFACE - FAILED TO START SERVER UDP","Failed Server",JOptionPane.ERROR_MESSAGE);
           
        } 
       
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        server_label = new javax.swing.JLabel();
        refresh_btn = new javax.swing.JButton();
        active_clients_label = new javax.swing.JLabel();
        num_of_users_label = new javax.swing.JLabel();
        slow_mode_btn = new javax.swing.JRadioButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        directory_table = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        server_label.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        server_label.setForeground(new java.awt.Color(51, 153, 255));
        server_label.setText("SERVER");

        refresh_btn.setBackground(new java.awt.Color(51, 153, 255));
        refresh_btn.setText("Refresh");
        refresh_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refresh_btnActionPerformed(evt);
            }
        });

        active_clients_label.setText("Active Users:");

        num_of_users_label.setText("0");

        slow_mode_btn.setBackground(new java.awt.Color(51, 153, 255));
        slow_mode_btn.setText("Slow Mode");
        slow_mode_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                slow_mode_btnActionPerformed(evt);
            }
        });

        directory_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "File", "Size", "IP Address", "Port"
            }
        ));
        directory_table.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(directory_table);

        jTextArea1.setBackground(new java.awt.Color(0, 0, 0));
        jTextArea1.setColumns(20);
        jTextArea1.setForeground(new java.awt.Color(51, 204, 0));
        jTextArea1.setRows(5);
        jTextArea1.setText("Server started.");
        jScrollPane2.setViewportView(jTextArea1);

        jLabel1.setText("Server Log:");

        jLabel2.setText("Available clients files:");

        jButton1.setText("Clear Log");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 637, Short.MAX_VALUE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(server_label)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(refresh_btn)
                                .addGap(18, 18, 18)
                                .addComponent(slow_mode_btn)
                                .addGap(18, 18, 18)
                                .addComponent(active_clients_label)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(num_of_users_label, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel2))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(server_label)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(refresh_btn)
                    .addComponent(slow_mode_btn)
                    .addComponent(active_clients_label)
                    .addComponent(num_of_users_label))
                .addGap(7, 7, 7)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 498, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void slow_mode_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_slow_mode_btnActionPerformed
        if(slow_mode_btn.isSelected())
        {
            server.setSlowMode(true);
        }
        else
        {
            server.setSlowMode(false);
        }
    }//GEN-LAST:event_slow_mode_btnActionPerformed

    private void refresh_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refresh_btnActionPerformed
        this.model.fireTableDataChanged();
        //System.out.println("INTERFACE - Refresh Instantiated [SERVER]");
        jTextArea1.append("\nINTERFACE - Refresh Instantiated [SERVER]\n");

    }//GEN-LAST:event_refresh_btnActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        jTextArea1.setText("");
    }//GEN-LAST:event_jButton1ActionPerformed

    public void hideWindow()
    {
        this.setVisible(false);
    }
    
    public void updateData(File mFile)
    {
        String[] data = {mFile.getName(), String.valueOf(mFile.length()), mFile.getAbsolutePath()};
        
        model.addRow(data);
        model.fireTableDataChanged();
    }
    
    public void clearTableModel(DefaultTableModel tbl)
    {
        if(tbl.getRowCount() > 0)
        {
            for(int i=tbl.getRowCount()-1; i>-1; i--)
            {
                tbl.removeRow(i);
            }
        }
    }
    
    public void updateModel(DefaultTableModel oldT, DefaultTableModel newT)
    {
        clearTableModel(oldT);
        for(int r=0; r<newT.getRowCount(); r++)
        {
            String[] data = {(newT.getValueAt(r,0).toString()),
                (newT.getValueAt(r,1).toString()),
                (newT.getValueAt(r,2).toString()),
                (newT.getValueAt(r,3).toString())
             };
            oldT.addRow(data);
        }
        
        oldT.fireTableDataChanged();
    }

    public void refreshDir(DefaultTableModel newDir)
    {
        updateModel(model, newDir);
    }
    /*
    public void refreshDirTable()
    {
        this.model.fireTableDataChanged();
        System.out.println("INTERFACE - Refresh Instantiated [SERVER]");
    }
    */
    public void refreshUsers(int num)
    {
        num_of_users_label.setText(String.valueOf(num));
        //this.invalidate();
        this.validate();
        //this.repaint();
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ServerMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ServerMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ServerMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ServerMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ServerMenu("").setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel active_clients_label;
    private javax.swing.JTable directory_table;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    public javax.swing.JTextArea jTextArea1;
    private javax.swing.JLabel num_of_users_label;
    private javax.swing.JButton refresh_btn;
    private javax.swing.JLabel server_label;
    private javax.swing.JRadioButton slow_mode_btn;
    // End of variables declaration//GEN-END:variables
}
