/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package edu.ccsu.networking.ui;

import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
/**
 *
 * @author Ben and Khaled
 */
public class StartUp extends JFrame {
    /**
     * Creates new form StartUp
     */
    public StartUp() {
        super("THE FUN FILE SHARE");
        initComponents();
        setLocationRelativeTo(this); //screen center.
        this.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        client_panel = new javax.swing.JPanel();
        client_label = new javax.swing.JLabel();
        server_addr_txtfield = new javax.swing.JTextField();
        server_address_label = new javax.swing.JLabel();
        server_port_label = new javax.swing.JLabel();
        server_port_txtfield = new javax.swing.JTextField();
        client_port_label = new javax.swing.JLabel();
        client_port_txtfield = new javax.swing.JTextField();
        start_client_btn = new javax.swing.JButton();
        server_panel = new javax.swing.JPanel();
        server_label = new javax.swing.JLabel();
        server_port_label2 = new javax.swing.JLabel();
        server_port_txtfield2 = new javax.swing.JTextField();
        start_server_btn = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(0, 0));
        setResizable(false);

        client_panel.setBorder(new javax.swing.border.MatteBorder(null));

        client_label.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        client_label.setText("CLIENT");

        server_address_label.setText("SERVER ADDRESS:");

        server_port_label.setText("SERVER PORT:");

        client_port_label.setText("CLIENT PORT:");

        start_client_btn.setText("Start Client");
        start_client_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                start_client_btnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout client_panelLayout = new javax.swing.GroupLayout(client_panel);
        client_panel.setLayout(client_panelLayout);
        client_panelLayout.setHorizontalGroup(
            client_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(client_panelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(client_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(server_address_label)
                    .addComponent(server_port_label)
                    .addComponent(client_label)
                    .addComponent(client_port_label))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(client_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(server_port_txtfield, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 175, Short.MAX_VALUE)
                    .addComponent(client_port_txtfield)
                    .addComponent(server_addr_txtfield, javax.swing.GroupLayout.Alignment.LEADING))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(client_panelLayout.createSequentialGroup()
                .addGap(187, 187, 187)
                .addComponent(start_client_btn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        client_panelLayout.setVerticalGroup(
            client_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(client_panelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(client_label)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(client_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(server_address_label)
                    .addComponent(server_addr_txtfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(client_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(server_port_txtfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(client_panelLayout.createSequentialGroup()
                        .addComponent(server_port_label, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(3, 3, 3)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(client_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(client_port_label)
                    .addComponent(client_port_txtfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(start_client_btn)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        server_panel.setBorder(new javax.swing.border.MatteBorder(null));

        server_label.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        server_label.setText("SERVER");

        server_port_label2.setText("PORT:");

        start_server_btn.setText("Start Server");
        start_server_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                start_server_btnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout server_panelLayout = new javax.swing.GroupLayout(server_panel);
        server_panel.setLayout(server_panelLayout);
        server_panelLayout.setHorizontalGroup(
            server_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(server_panelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(server_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(server_panelLayout.createSequentialGroup()
                        .addComponent(server_label)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(server_panelLayout.createSequentialGroup()
                        .addComponent(server_port_label2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(server_port_txtfield2, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(start_server_btn, javax.swing.GroupLayout.DEFAULT_SIZE, 94, Short.MAX_VALUE)))
                .addContainerGap())
        );
        server_panelLayout.setVerticalGroup(
            server_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(server_panelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(server_label)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(server_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(server_port_label2)
                    .addComponent(server_port_txtfield2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(start_server_btn))
                .addContainerGap(23, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(server_panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(client_panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jSeparator1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(client_panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(server_panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

   public void hideWindow()
   {
       this.setVisible(false);
   }
    
    private void start_client_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_start_client_btnActionPerformed
        if(server_addr_txtfield.getText().isEmpty() || 
                server_port_txtfield.getText().isEmpty() ||
                client_port_txtfield.getText().isEmpty())
        {
            //System.out.println("INTERFACE - ERROR: EMPTY FIELDS [CLIENT]");
            JOptionPane.showMessageDialog(null,"INTERFACE - ERROR:  EMPTY FIELDS [CLIENT]","Required ...",JOptionPane.ERROR_MESSAGE);
        }
        else
        {
            hideWindow();
            ClientMenu client = new ClientMenu(server_addr_txtfield.getText(), 
                    server_port_txtfield.getText(), 
                    client_port_txtfield.getText());
        }
    }//GEN-LAST:event_start_client_btnActionPerformed

    private void start_server_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_start_server_btnActionPerformed
        if(server_port_txtfield2.getText().isEmpty() )
        {
            //System.out.println("INTERFACE - ERROR: EMPTY FIELDS [SERVER]");
             JOptionPane.showMessageDialog(null,"INTERFACE - ERROR:  EMPTY FIELDS [SERVER]","Required ...",JOptionPane.ERROR_MESSAGE);
        }
        else
        {
            hideWindow();
            ServerMenu server = new ServerMenu(server_port_txtfield2.getText() );
        }
    }//GEN-LAST:event_start_server_btnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StartUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StartUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StartUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StartUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form 
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StartUp().setVisible(true);
            }
        });
*/
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel client_label;
    private javax.swing.JPanel client_panel;
    private javax.swing.JLabel client_port_label;
    private javax.swing.JTextField client_port_txtfield;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField server_addr_txtfield;
    private javax.swing.JLabel server_address_label;
    private javax.swing.JLabel server_label;
    private javax.swing.JPanel server_panel;
    private javax.swing.JLabel server_port_label;
    private javax.swing.JLabel server_port_label2;
    private javax.swing.JTextField server_port_txtfield;
    private javax.swing.JTextField server_port_txtfield2;
    private javax.swing.JButton start_client_btn;
    private javax.swing.JButton start_server_btn;
    // End of variables declaration//GEN-END:variables
}
